# SPDX-FileCopyrightText: 2025 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

codecov:
  branch: main
  strict_yaml_branch: main
  max_report_age: 12h
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 90..100

  status:
    project:
      default:
        target: 95%
        threshold: 1%
        base: auto
        if_ci_failed: error
        only_pulls: false

    patch:
      default:
        target: 95%
        threshold: 1%
        base: auto
        if_ci_failed: error

    changes:
      default:
        base: auto
        if_ci_failed: error

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  show_carryforward_flags: true
  hide_project_coverage: false

ignore:
  - "imir/benches/**/*"
  - "imir/examples/**/*"
  - "imir/tests/**/*"
  - "**/test_*.rs"
  - "**/*_test.rs"
  - ".github/**/*"
  - "assets/**/*"
  - "metrics/**/*"
  - "targets/**/*"

component_management:
  individual_components:
    - component_id: core
      name: Core Library
      paths:
        - imir/src/config.rs
        - imir/src/error.rs
        - imir/src/normalizer.rs

    - component_id: discovery
      name: Discovery System
      paths:
        - imir/src/discover.rs
        - imir/src/badge.rs

    - component_id: git_ops
      name: Git Operations
      paths:
        - imir/src/git.rs
        - imir/src/gh.rs

    - component_id: rendering
      name: Rendering System
      paths:
        - imir/src/render.rs
        - imir/src/readme.rs
        - imir/src/slug.rs
        - imir/src/slugs.rs
        - imir/src/artifact.rs
        - imir/src/retry.rs
        - imir/src/contributors.rs

flags:
  unit:
    paths:
      - imir/src/**/*.rs
    carryforward: false

  integration:
    paths:
      - imir/tests/**/*.rs
    carryforward: false

github_checks:
  annotations: true
