[advisories]
ignore = []
git-fetch-with-cli = true

[bans]
multiple-versions = "warn"
wildcards = "allow"
deny = []

[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0", "ISC", "BSD-3-Clause"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
