name: Badge sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - main
    paths:
      - README.md
      - targets/targets.yaml
  pull_request:
    paths:
      - README.md
      - targets/targets.yaml

permissions:
  contents: read
  pull-requests: read

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TARGETS_CONFIG: targets/targets.yaml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup IMIR
        uses: ./.github/actions/setup-imir
        with:
          token: ${{ secrets.CLASSIC || github.token }}

      - name: Normalize targets document
        id: targets
        run: |
          set -euo pipefail

          imir --config "${TARGETS_CONFIG}" > targets.json

          echo "path=targets.json" >> "$GITHUB_OUTPUT"

      - name: Detect impacted badge slugs
        id: slugs
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha || '' }}
          PUSH_BEFORE_SHA: ${{ github.event.before || '' }}
          HEAD_SHA: ${{ github.sha }}
        run: |
          set -euo pipefail

          TARGETS_JSON="${{ steps.targets.outputs.path }}"
          if [ -z "${TARGETS_JSON}" ] || [ ! -f "${TARGETS_JSON}" ]; then
            echo "Targets JSON is missing." >&2
            exit 1
          fi

          ALL_SLUGS_JSON="$(jq -c '[.targets[].slug]' "${TARGETS_JSON}")"

          if [ "${EVENT_NAME}" = "schedule" ]; then
            SELECTED="${ALL_SLUGS_JSON}"
          else
            BASE_REF=""
            if [ "${EVENT_NAME}" = "pull_request" ]; then
              BASE_REF="${PR_BASE_SHA}"
            elif [ "${EVENT_NAME}" = "push" ]; then
              BASE_REF="${PUSH_BEFORE_SHA}"
            fi

            if [ -n "${BASE_REF}" ]; then
              if ! git rev-parse --verify "${BASE_REF}" >/dev/null 2>&1; then
                git fetch --no-tags --prune --depth=1 origin "+${BASE_REF}:${BASE_REF}" || true
              fi
            fi

            HEAD_REF="${HEAD_SHA}"
            if [ -z "${HEAD_REF}" ]; then
              HEAD_REF="$(git rev-parse HEAD)"
            fi

            if [ -n "${BASE_REF}" ]; then
              DIFF_OUTPUT="$(git diff --unified=0 "${BASE_REF}" "${HEAD_REF}" -- README.md targets/targets.yaml || true)"
            else
              DIFF_OUTPUT="$(git show "${HEAD_REF}" -- README.md targets/targets.yaml || true)"
            fi

            SLUGS_FROM_DIFF="$(printf '%s' "${DIFF_OUTPUT}" | grep -oE 'metrics/([A-Za-z0-9_.-]+)\\.svg' || true)"
            if [ -n "${SLUGS_FROM_DIFF}" ]; then
              SLUGS="$(printf '%s' "${SLUGS_FROM_DIFF}" | sed -E 's#metrics/##;s#\\.svg##' | sort -u)"
            else
              SLUGS=""
            fi

            if [ -n "${SLUGS}" ]; then
              SELECTED="$(printf '%s\n' "${SLUGS}" | jq -Rsc 'split("\n") | map(select(length > 0))')"
            else
              SELECTED="[]"
            fi
          fi

          echo "slugs=${SELECTED}" >> "$GITHUB_OUTPUT"
          if [ "${SELECTED}" != "[]" ]; then
            echo "has=true" >> "$GITHUB_OUTPUT"
          else
            echo "has=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate badge assets
        if: steps.slugs.outputs.has == 'true'
        env:
          SLUGS_JSON: ${{ steps.slugs.outputs.slugs }}
        run: |
          set -euo pipefail

          printf '%s' "${SLUGS_JSON}" | jq -r '.[]' | while read -r SLUG; do
            if [ -z "${SLUG}" ]; then
              continue
            fi

            echo "Rendering badge for ${SLUG}" >&2
            imir badge generate --config "${TARGETS_CONFIG}" --target "${SLUG}" --output metrics
          done

      - name: Commit badge updates
        id: commit
        if: steps.slugs.outputs.has == 'true' && github.event_name != 'pull_request'
        run: |
          set -euo pipefail

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add metrics

          if git diff --cached --quiet; then
            echo "No badge changes to commit."
            exit 0
          fi

          git commit -m "chore(badges): refresh"
          git push origin main

