# SPDX-FileCopyrightText: 2025 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(imir): bump version')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Set up nightly toolchain for rustfmt
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Install cargo utilities
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit,cargo-tarpaulin

      - name: Install reuse tool
        run: pip install reuse

      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "imir -> target"

      - name: "[1/9] Formatting"
        run: cargo +nightly fmt --check --manifest-path imir/Cargo.toml

      - name: "[2/9] Clippy"
        run: cargo +stable clippy --all-targets --all-features --manifest-path imir/Cargo.toml -- -D warnings

      - name: "[3/9] Tests"
        run: cargo +stable test --all-features --manifest-path imir/Cargo.toml

      - name: "[4/9] Coverage"
        run: cargo +stable tarpaulin --all-features --out Xml --manifest-path imir/Cargo.toml

      - name: "[5/9] Benchmarks"
        run: cargo +stable bench --no-fail-fast --manifest-path imir/Cargo.toml

      - name: "[6/9] Build"
        run: cargo +stable build --release --all-features --manifest-path imir/Cargo.toml

      - name: "[7/9] Audit"
        run: cargo +stable audit --file imir/Cargo.lock

      - name: "[8/9] Docs"
        run: cargo +stable doc --no-deps --all-features --manifest-path imir/Cargo.toml

      - name: "[9/9] License compliance"
        run: reuse lint
