name: Release IMIR binaries

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    name: Build x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    env:
      ARCHIVE: imir-x86_64-unknown-linux-gnu.tar.gz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release --locked --manifest-path imir/Cargo.toml

      - name: Package binary
        run: |
          set -euo pipefail
          BIN="imir/target/release/imir"
          chmod +x "${BIN}"
          tar -C "$(dirname "${BIN}")" -czf "${ARCHIVE}" "$(basename "${BIN}")"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARCHIVE }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
