# SPDX-FileCopyrightText: 2025 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Render metrics for masterror repository

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch name used for the metrics refresh PR."
        required: false
        default: "ci/metrics-refresh-masterror"
  workflow_call:
    inputs:
      branch_name:
        description: "Branch name used for the metrics refresh PR."
        required: false
        default: "ci/metrics-refresh-masterror"
        type: string
    secrets:
      CLASSIC:
        required: true

jobs:
  render:
    uses: ./.github/workflows/render-repository.yml
    with:
      branch_name: ${{ inputs.branch_name }}
      contributors_branch: main
      target_owner: RAprogramm
      target_repo: masterror
      target_path: metrics/masterror.svg
      temp_artifact: .metrics-tmp/masterror.svg
    secrets:
      CLASSIC: ${{ secrets.CLASSIC }}
