name: Render metrics (skeleton)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Say hello
        run: echo "Metrics center is alive!"

