name: Render metrics for telegram-webapp-sdk repository

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch name used for the metrics refresh PR."
        required: false
        default: "ci/metrics-refresh-telegram-webapp-sdk"
  workflow_call:
    inputs:
      branch_name:
        description: "Branch name used for the metrics refresh PR."
        required: false
        default: "ci/metrics-refresh-telegram-webapp-sdk"
        type: string
    secrets:
      CLASSIC:
        required: true

jobs:
  render:
    uses: ./.github/workflows/render-repository.yml
    with:
      branch_name: ${{ inputs.branch_name }}
      target_owner: RAprogramm
      target_repo: telegram-webapp-sdk
      target_path: metrics/telegram-webapp-sdk.svg
      temp_artifact: repo.tmp.svg
    secrets:
      CLASSIC: ${{ secrets.CLASSIC }}
