name: Render metrics for selected targets

on:
  schedule:
    - cron: "19 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  masterror:
    uses: ./.github/workflows/render-masterror.yml
    with:
      branch_name: ci/metrics-refresh-masterror
    secrets:
      CLASSIC: ${{ secrets.CLASSIC }}

  profile:
    uses: ./.github/workflows/render-profile.yml
    with:
      branch_name: ci/metrics-refresh-profile
    secrets:
      CLASSIC: ${{ secrets.CLASSIC }}

  telegram_webapp_sdk:
    uses: ./.github/workflows/render-telegram-webapp-sdk.yml
    with:
      branch_name: ci/metrics-refresh-telegram-webapp-sdk
    secrets:
      CLASSIC: ${{ secrets.CLASSIC }}
