name: Render metrics for open-source repositories

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: >-
          JSON array with repository names that should be refreshed.
          Defaults to ["masterror", "telegram-webapp-sdk"].
        required: false
        default: '["masterror", "telegram-webapp-sdk"]'
  workflow_call:
    inputs:
      repositories:
        description: >-
          JSON array with repository names that should be refreshed.
          Defaults to ["masterror", "telegram-webapp-sdk"].
        required: false
        type: string
        default: '["masterror", "telegram-webapp-sdk"]'
    secrets:
      CLASSIC:
        required: true

jobs:
  render:
    strategy:
      matrix:
        repository: ${{ fromJSON(inputs.repositories != '' ? inputs.repositories : '["masterror", "telegram-webapp-sdk"]') }}
    uses: ./.github/workflows/render-repository.yml
    with:
      branch_name: ${{ format('ci/metrics-refresh-{0}', matrix.repository) }}
      target_owner: RAprogramm
      target_repo: ${{ matrix.repository }}
      target_path: ${{ format('metrics/{0}.svg', matrix.repository) }}
      temp_artifact: ${{ format('.metrics-tmp/{0}.svg', matrix.repository) }}
    secrets:
      CLASSIC: ${{ secrets.CLASSIC }}
