name: Render metrics for open-source repositories

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: >-
          JSON array with repository descriptors that should be refreshed.
          Each entry may be a repository string or an object with
          `repository` and optional `contributors_branch`.
        required: false
        default: '[{"repository":"masterror"}, {"repository":"telegram-webapp-sdk"}]'
  workflow_call:
    inputs:
      repositories:
        description: >-
          JSON array with repository descriptors that should be refreshed.
          Each entry may be a repository string or an object with
          `repository` and optional `contributors_branch`.
        required: false
        type: string
        default: '[{"repository":"masterror"}, {"repository":"telegram-webapp-sdk"}]'
    secrets:
      CLASSIC:
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.resolve.outputs.targets }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache imir build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "imir -> target"

      - id: resolve
        name: Resolve repository list
        env:
          RAW_INPUT: ${{ inputs.repositories }}
        run: |
          set -euo pipefail
          RAW="${RAW_INPUT:-}"
          TARGETS=$(cargo run --manifest-path imir/Cargo.toml --quiet --locked -- open-source --input "${RAW}")
          printf 'targets=%s\n' "${TARGETS}" >> "${GITHUB_OUTPUT}"

  render:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.prepare.outputs.targets) }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Render metrics for ${{ matrix.target.repository }}
        uses: ./.github/actions/render-repository
        with:
          classic_token: ${{ secrets.CLASSIC }}
          target_owner: RAprogramm
          target_repo: ${{ matrix.target.repository }}
          branch_name: ${{ format('ci/metrics-refresh-{0}', matrix.target.repository) }}
          contributors_branch: ${{ matrix.target.contributors_branch }}
          target_path: ${{ format('metrics/{0}.svg', matrix.target.repository) }}
          temp_artifact: ${{ format('.metrics-tmp/{0}.svg', matrix.target.repository) }}
