# SPDX-FileCopyrightText: 2025 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Render metrics for RAprogramm profile

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CLASSIC:
        required: true

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Render profile metrics
        uses: ./.github/actions/render-profile
        with:
          classic_token: ${{ secrets.CLASSIC }}
          target_user: RAprogramm
          target_path: metrics/profile.svg
          temp_artifact: .metrics-tmp/profile.svg
          time_zone: Asia/Ho_Chi_Minh
          display_name: profile
          include_private: true
