# SPDX-FileCopyrightText: 2025 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Render metrics for telegram-webapp-sdk repository

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CLASSIC:
        required: true

jobs:
  render:
    uses: ./.github/workflows/render-repository.yml
    with:
      contributors_branch: main
      target_owner: RAprogramm
      target_repo: telegram-webapp-sdk
      target_path: metrics/telegram-webapp-sdk.svg
      temp_artifact: .metrics-tmp/telegram-webapp-sdk.svg
    secrets:
      CLASSIC: ${{ secrets.CLASSIC }}
