name: Render metrics for selected targets

on:
  schedule:
    - cron: "19 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  open_source:
    uses: ./.github/workflows/render-open-source.yml
    with:
      repositories: '["masterror", "telegram-webapp-sdk"]'
    secrets:
      CLASSIC: ${{ secrets.CLASSIC }}

  profile:
    uses: ./.github/workflows/render-profile.yml
    with:
      branch_name: ci/metrics-refresh-profile
    secrets:
      CLASSIC: ${{ secrets.CLASSIC }}
